adding things

diff --git a/lib/ioScreen b/lib/ioScreen
--- a/lib/ioScreen
+++ b/lib/ioScreen
@@ -1,5 +1,7 @@
 #!/bin/zsh
 
+#!/bin/zsh
+
 function ioScreen.defineColors {
   noColor='\033[0m'
   black='\033[0;30m'
@@ -39,8 +41,10 @@ function ioScreen.outWarn {
 ##  $2 line number
 ##
 function ioScreen.outError {
-  printf "${red}[ ${lightRed}ERROR ${red}]${noColor}\tStatus Code: ${1}\n\t\tLine Number: ${2}\n\t\tExiting script.\n"
-  exit $1
+  printf "${red}[ ${lightRed}ERROR ${red}]\n \
+    ${1}\n \
+    Exiting script.${noColor}\n" \
+    exit 1
 }
 
 ##  Display a seperator that is the full width of the terminal
@@ -52,33 +56,22 @@ function ioScreen.outError {
 ##
 ##  Usage Example:
 ##    ioScreen.horizontal.seperator +  # creates a horziontal line made of +
-function ioScreen.horizontal.seperator {
-  lineChar=${1}
-  if [[ -z ${lineChar} ]]; then
-    lineChar="-"
-  fi
-  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' ${lineChar}
+function horizontal_separator() {
+  local lineChar="${1:-"-"}"
+  printf '%*s' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "${lineChar}"
 }
 
-function ioScreen.stdHeader {
+## Display a standard header
+## uses the function:  ioScreen.horizontal.seperator
+function ioScreen.stdHeader() {
   local headerText=${1} # text to display in the header
-  if [[ -z ${2} ]]; then
-    local optChar='-'
-  else
-    local optChar=${2}
-  fi
+  local optChar=${2:-'-'}
   printf '\n'
-  ioScreen.horizontal.seperator ${optChar}
-  printf "\t${headerText}\n"
-  ioScreen.horizontal.seperator ${optChar}
+  ioScreen.horizontal.seperator "${optChar}"
+  printf "\t%s" "${headerText}"
+  ioScreen.horizontal.seperator "${optChar}"
   printf '\n'
   unset headerText
-}
-function ioScreen.outError {
-  printf "${red}[ ${lightRed}ERROR ${red}]\t${1}\n 
-    \t\tLine Number: ${2}\n
-    \t\tExiting script.${noColor}\n"
-  exit 1
 }
 
 ioScreen.defineColors
